const $ = s => document.querySelector(s);
const paths={home:'M3 10 12 3l9 7v10H4V10m5 10v-7h6v7',spark:'m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0V5M6 10v2a6 6 0 0 0 12 0v-2M12 18v4m-4 0h8',device:'M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m3 3h4m-2 12v1',book:'M3 4h7l2 2 2-2h7v15h-7l-2 2-2-2H3V4m9 2v15',search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0m-2 5 7 7',upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6',file:'M6 2h8l5 5v15H6V2m8 0v6h5M9 12h7m-7 4h7',edit:'m4 16 12-12 4 4L8 20H4v-4m10-10 4 4',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 7v5l3 2',heart:'M12 21 3 12C-3 4 7-1 12 6c5-7 15-2 9 6Z'};
const icon=n=>`<span class="icon"><svg viewBox="0 0 24 24"><path d="${paths[n]||paths.file}"/></svg></span>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initial=()=>({logged:false,bound:false,course:0,lesson:0,courses:[{name:'宏观经济学',icon:'↗',color:'',lessons:[{name:'第 3 课 · 课程知识与应用',ready:true},{name:'第 2 课 · 核心概念梳理',ready:true},{name:'第 1 课 · 课程导论',ready:true}]},{name:'中国近代史纲要',icon:'册',color:'purple',lessons:[{name:'第 1 课 · 课程导论',ready:true}]},{name:'Python 数据分析',icon:'⌘',color:'peach',lessons:[]}]});
const galleryMode=new URLSearchParams(location.search).has('gallery');
let state;try{state=JSON.parse(localStorage.getItem('yuni-prototype-v1'))||initial()}catch{state=initial()}
if(galleryMode)state=initial();
let pendingLoginAction=null;
let route='',historyStack=[],noteTab=0,editSource=true,recordState='idle',recordSeconds=0,recordMode='phone',transferProgress=0,processingStep=0,question=0,filter='all',transcriptIndex=0,playerOn=false,playerSeconds=0,chats=[],aiScope='lesson',timer,toastTimer;
const save=()=>{if(galleryMode)return;try{localStorage.setItem('yuni-prototype-v1',JSON.stringify(state))}catch{}};
const course=()=>state.courses[state.course]||state.courses[0];
const lesson=()=>course().lessons[state.lesson];
const freshStudy=()=>({note:'本节课围绕核心概念、知识点之间的联系与典型应用展开。复习时，先理解概念，再结合课堂例子完成练习。',marked:false,remark:'',answers:[null,null,null],submitted:false});
const emptyStudy=freshStudy();
if(galleryMode){state.logged=true;state.bound=true;state.courses[0].lessons[0].study={...freshStudy(),answers:[1,[0,1],'回顾知识、完成练习、回看原文。'],submitted:true};}
function study(){const l=lesson();if(!l)return emptyStudy;if(!l.study)l.study=freshStudy();return l.study;}
const currentName=()=>lesson()?.name||'尚未添加课时';
const pages={
 login:['微信登录','通过微信授权建立账户；原型用模拟授权展示成功与取消状态。',['新增 Must'],['勾选协议并模拟微信授权','登录后进入课程首页']],
 home:['首页','学习的日常入口：查看课程、连接录音卡、开始记录一堂课。',['原版课程列表','新增 Must：课时'],['打开课程与课时','新建课程','开始录音或设备管理']],
 course:['课程详情','将原版课程成果组织到课时下，便于长期归档和回顾。',['原版课程结构','新增 Must'],['搜索课时','打开已有课时','录制或导入新课时']],
 lesson:['课时详情','保留录音、AI 笔记、考点复习、押题批阅四阶段及前置依赖。',['原版学习链路'],['进入四个成果阶段','未生成课时显示锁定状态','生成后解锁学习成果']],
 capture:['记录一堂课','补齐硬件录音与小程序录音；保留原版音频文件导入。',['新增 Must：双录音入口'],['选择归属课程','小程序录音','录音卡采集和文件回传']],
 record:['课堂录音','小程序录音可开始、暂停、结束；硬件模式模拟实体按键，展示状态同步。',['新增 Must'],['开始与结束模拟录音','暂停及继续小程序录音','结束后归档或回传']],
 transfer:['录音卡文件回传','展示硬件采集到软件处理的衔接；传输方式待硬件规格确认。',['新增 Must：硬件回传'],['模拟传输进度','取消后重试','回传后进入转写与生成']],
 processing:['转写与生成','将转写、摘要生成、索引关联作为明确的可见处理状态。',['原版转写','新增 Must：结构化笔记'],['模拟生成阶段','完成后进入笔记','回到首页后可继续处理']],
 notes:['AI 课堂笔记','课程概要、知识要点与原版思维导图；支持修改、重点标记、备注与原文回溯。',['原版摘要 / 思维导图','新增 Must：编辑与溯源'],['切换笔记模块','长按要点调出操作','点击原文定位到时间点']],
 edit:['编辑笔记','修改 AI 笔记时展示对应原始转写；保存后更新笔记正文。',['新增 Must：校正 / 对照'],['增删改笔记正文','重点标记与备注','保存或取消修改']],
 transcript:['录音与原文','从笔记定位原始转写段落，对应时间点高亮；播放器为交互模拟。',['原版录音 / 转写','新增 Must：原文定位'],['切换对应转写段落','拖动模拟音频进度','返回笔记进行校正']],
 review:['考点与复习','保留原版重点、考点和复习建议，并将试卷入口串联起来。',['原版复习能力'],['浏览知识重点与建议','回溯对应笔记','进入押题练习']],
 exam:['押题练习','原版试卷改为移动端逐题作答；包含单选、多选与简答演示，提交后查看批阅。',['原版试卷'],['逐题选择或填写答案','切换题号并保留答案','确认提交与未答提醒']],
 results:['试卷批阅','保留得分、逐题答案、解析与薄弱知识点，并提供复习回路。',['原版批阅 / 导出'],['查看逐题解析','返回复习或重做','打印 / 保存 PDF']],
 ai:['AI 学习助手','按草图设置独立 AI 标签，问答限定于选定课程或课时，回答附笔记来源。',['新增 Should：轻量问答'],['选择课程与问答范围','输入问题或点击示例','点击回答来源回到笔记']],
 mine:['我的','账户、硬件设备与已有功能额度统一管理。',['新增 Must：账户 / 设备','保留额度信息'],['查看设备状态','查看原版次数规则说明','切换登录状态']],
 device:['我的录音卡','绑定、连接、电量、存储、录音与待回传文件集中展示。',['新增 Must：硬件管理'],['模拟发现与绑定设备','开始硬件录音','回传待处理文件']]
};
const groups=[['开始',['login','home','course','lesson']],['采集与整理',['capture','record','transfer','processing','notes','edit','transcript']],['复习与服务',['review','exam','results','ai','mine','device']]];
function renderCatalog(){let i=0;$('#catalog').innerHTML=groups.map(([name,items])=>`<div class="nav-group">${name}</div>${items.map(id=>`<button class="nav-item ${id===route?'active':''}" onclick="preview('${id}')"><span>${String(++i).padStart(2,'0')}</span>${pages[id][0]}</button>`).join('')}`).join('')}
function preview(id){if(['lesson','notes','edit','transcript','review','exam','results'].includes(id)&&!lesson()){state.course=0;state.lesson=0}go(id)}
function go(id){if(!pages[id])id='home';if(route&&route!==id)historyStack.push(route);route=id;location.hash=id;render()}
function goBack(){const fallback={edit:'notes',transcript:'notes',notes:'lesson',review:'lesson',exam:'review',results:'lesson',record:'capture',transfer:'capture',processing:'lesson',capture:'course',device:'mine',lesson:'course',course:'home',login:'home'};goWithoutHistory(historyStack.pop()||fallback[route]||'home')}
function goWithoutHistory(id){route=id;location.hash=id;render()}
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(id!==route){route=pages[id]?id:'home';render()}});
function render(){clearInterval(timer);$('#overlay').innerHTML='';$('#page-title').textContent=route==='home'?'芋泥 · 课堂笔记':pages[route][0];$('#back').style.visibility=['home','ai','mine'].includes(route)?'hidden':'visible';$('#screen').innerHTML=(!lesson()&&['lesson','notes','edit','transcript','review','exam','results'].includes(route))?'<div class="empty">这门课还没有课时，先记录一堂课吧。</div><button class="primary" onclick="go(\'capture\')">记录一堂课</button>':views[route]();$('#screen').scrollTop=0;$('#tabbar').innerHTML=['home','ai','mine'].includes(route)?`<div class="tabs">${[['home','home','首页'],['ai','spark','AI'],['mine','user','我的']].map(([r,i,t])=>`<button class="tab ${route===r?'on':''}" onclick="go('${r}')">${icon(i)}${t}</button>`).join('')}</div>`:'';const p=pages[route];$('#spec-title').textContent=p[0];$('#spec-copy').textContent=p[1];$('#spec-tags').innerHTML=p[2].map(t=>`<span class="tag ${t.includes('新增')?'new':''}">${t}</span>`).join('');$('#spec-actions').innerHTML=`<ol>${p[3].map(t=>`<li>${t}</li>`).join('')}</ol>`;renderCatalog();if(route==='record'&&recordState==='recording')startRecordTimer();if(route==='transfer'&&transferProgress>0&&transferProgress<100)startTransferTimer();if(route==='processing'&&processingStep<3)startProcessingTimer();if(route==='transcript'&&playerOn)startPlayerTimer();}
function toast(s){clearTimeout(toastTimer);$('#toast').textContent=s;$('#toast').style.display='block';toastTimer=setTimeout(()=>$('#toast').style.display='none',2600)}
function sheet(title,body){$('#overlay').innerHTML=`<div class="sheet"><button class="close" aria-label="关闭弹窗" onclick="closeSheet()">×</button><h3>${title}</h3>${body}</div>`}
function closeSheet(){$('#overlay').innerHTML=''}
function resetDemo(){sheet('重置演示数据','<p>将清除本原型创建的课程、编辑内容与答题记录，恢复示例状态。</p><button class="primary" onclick="state=initial();save();historyStack=[];recordState=\'idle\';processingStep=0;transferProgress=0;chats=[];go(\'home\')">确认重置</button>')}
function selectCourse(index){state.course=Number(index);state.lesson=0;chats=[];save();if(route==='ai')render()}
function openCourse(index){selectCourse(index);go('course')}
function openLesson(index){state.lesson=index;save();go('lesson')}
function newCourse(){if(!state.logged){pendingLoginAction=newCourse;go('login');toast('登录后创建自己的课程');return}sheet('新建课程',`<p>为一门课程建立空间，每次上课单独归档为课时。</p><label class="label" for="course-name">课程名称</label><input id="course-name" class="field" maxlength="30" placeholder="例如：高等数学"><p class="muted">原版有次数确认；原型不执行实际扣费。</p><button class="primary" onclick="createCourse()">创建课程</button>`)}
function createCourse(){const name=$('#course-name').value.trim();if(!name)return toast('请填写课程名称');state.courses.push({name,icon:'册',color:'',lessons:[]});selectCourse(state.courses.length-1);go('course');toast('课程已创建，开始记录第一堂课吧')}
const courseSelect=(id='course-select')=>`<select id="${id}" class="field" onchange="selectCourse(this.value)">${state.courses.map((c,i)=>`<option value="${i}" ${i===state.course?'selected':''}>${esc(c.name)}</option>`).join('')}</select>`;
const courseCards=()=>state.courses.map((c,i)=>`<article class="course-card" onclick="openCourse(${i})" tabindex="0" onkeydown="if(event.key==='Enter')openCourse(${i})"><div class="cover ${c.color}">${c.icon}</div><div><h3>${esc(c.name)}</h3><p>${c.lessons.length} 个课时 · ${c.lessons.filter(l=>l.ready).length} 份课堂笔记</p><small>${c.lessons.length?'上次学习 · '+esc(c.lessons[0].name.split(' · ')[0]):'等待记录第一堂课'}</small></div><span class="chevron">›</span></article>`).join('');
function getLessonList(query=''){const rows=course().lessons.map((l,i)=>({l,i})).filter(({l})=>(filter!=='ready'||l.ready)&&l.name.includes(query));return rows.length?rows.map(({l,i})=>`<div class="lesson" onclick="openLesson(${i})"><div class="row"><strong>${esc(l.name)}</strong><span class="pill ${l.ready?'':'orange'}">${l.ready?'可复习':'待生成'}</span></div><p>${l.ready?'课程录音已整理 · AI 笔记可编辑':'录音已归档 · 等待转写与生成'}</p><div class="lesson-foot"><span>${icon('clock')} ${l.duration||'45:00'}</span><span>${l.ready?'笔记 / 考点 / 试卷':'点击继续整理'}</span></div></div>`).join(''):'<div class="empty">这里还没有课时<br><br>录制或导入一堂课，开始积累知识。</div>'}
const views={
 home:()=>`<div class="greeting"><span>今天，也学有所获</span><span>LEARN A LITTLE MORE</span></div><h2>让课堂知识<br>有迹可循。</h2><div class="hero"><div class="hero-art"><b>✧</b><i></i><i></i><i></i></div><h3>好好听课，<br>笔记交给芋泥。</h3><p>录下课堂，整理重点，轻松复习</p><button class="primary" onclick="go('capture')">${icon('mic')} 记录一堂课</button></div><div class="device-strip" onclick="go('device')">${icon('device')}<div><strong>${state.bound?'芋泥录音卡 · 已连接':'连接你的录音卡'}</strong><small>${state.bound?'电量 86% · 1 个录音待回传':'按一下就开录，下课回传生成笔记'}</small></div><span class="chevron">›</span></div><div class="row section-title"><strong>我的课程 <small class="muted">${state.courses.length}</small></strong><button class="text-btn" onclick="newCourse()">＋ 新建课程</button></div>${courseCards()}`,
 login:()=>`<div class="login-art"><div class="hero-art"><b>芋</b><i></i><i></i><i></i></div></div><h2 class="center">每一堂课，都有收获。</h2><p class="sub center">记录课堂 · 整理笔记 · 陪你复习</p><div class="panel"><h3>欢迎来到芋泥</h3><p class="muted">使用微信登录，关联你的课程、笔记与录音卡。</p><label class="check"><input type="checkbox" id="agreement">我已阅读并同意用户协议与隐私说明（演示占位，正式上线需配置）。</label><button class="primary" onclick="login()">微信授权登录</button><button class="text-btn" style="display:block;margin:14px auto 0" onclick="go('home')">先看看示例课程</button></div><p class="fine center">本原型仅模拟授权，不获取真实微信信息。</p>`,
 course:()=>`<div class="course-heading"><div class="cover ${course().color}">${course().icon}</div><div><div class="greeting">MY COURSE</div><h2>${esc(course().name)}</h2><p class="sub">按课时积累，随时回顾</p></div></div><div class="stat-row"><div><b>${course().lessons.length}</b><span>已记录课时</span></div><div><b>${course().lessons.filter(l=>l.ready).length}</b><span>课堂笔记</span></div><div><b>${course().lessons.filter(l=>l.study?.marked).length}</b><span>标记重点</span></div></div><button class="primary" onclick="go('capture')">${icon('mic')} 记录新课时</button><div class="search">${icon('search')}<input placeholder="搜索这门课的课时" oninput="$('#lesson-list').innerHTML=getLessonList(this.value)"></div><div class="row section-title"><strong>课时笔记</strong><small class="muted">最近记录在前</small></div><div class="filters"><button class="chip ${filter==='all'?'on':''}" onclick="filter='all';render()">全部</button><button class="chip ${filter==='ready'?'on':''}" onclick="filter='ready';render()">可复习</button></div><div id="lesson-list">${getLessonList()}</div>`,
 lesson:()=>`<div class="greeting">${esc(course().name)}</div><h2 style="font-size:23px">${esc(currentName())}</h2><p class="sub">${lesson()?.duration||'45:00'} · ${lesson()?.ready?'内容已整理':'录音已归档'}</p><div class="banner">从课堂录音开始，逐步形成自己的复习资料。</div><div class="step-list">${[['mic','课程录音','回听录音，查看原始转写','transcript'],['spark','AI 摘要与结构化笔记','概要 / 要点 / 思维导图，可编辑','notes'],['book','考点与复习建议','聚焦重要知识，安排复习','review'],['file','押题试卷及批阅结果','完成练习，检查知识掌握情况',study().submitted?'results':'exam']].map(([ic,t,d,r],i)=>`<div class="step ${!lesson()?.ready&&i>0?'locked':''}" onclick="enterStage('${r}',${i})"><span class="step-num">${icon(ic)}</span><div class="step-main"><h3>${t}</h3><p>${d}</p></div><span class="step-status">${lesson()?.ready?'查看 ›':i===0?'已保存':'未解锁'}</span></div>`).join('')}</div>${!lesson()?.ready?'<button class="primary" onclick="beginProcessing()">生成转写与 AI 笔记</button>':'<button class="secondary" onclick="go(\'ai\')">围绕这堂课，问问 AI</button>'}`,
 capture:()=>`<h2>记录新的一堂课</h2><p class="sub">选择记录方式，课后自动整理成笔记</p><label class="label">归属课程</label>${courseSelect()}<div class="tile" onclick="startMode('phone')">${icon('mic')}<div><h3>小程序内录音</h3><p>没带录音卡，也能随时记录课堂</p></div><span class="chevron">›</span></div><div class="tile" onclick="startMode('hardware')">${icon('device')}<div><h3>使用录音卡</h3><p>实体按键一键录音，小程序同步状态</p></div><span class="chevron">›</span></div><div class="tile" onclick="importAudio()">${icon('upload')}<div><h3>导入已有录音</h3><p>M4A / MP3 / WAV / AAC</p></div><span class="chevron">›</span></div><div class="banner">录音按「课程 → 课时」保存。硬件文件回传后进入同一套转写与笔记流程。</div>`,
 record:()=>`<div class="row"><span class="pill">${recordMode==='hardware'?'录音卡 · 已连接':'小程序内录音'}</span><small class="muted">${esc(course().name)}</small></div><div class="recorder"><div class="record-orb ${recordState==='recording'?'recording':''}">${icon('mic')}</div><h3>${recordState==='recording'?'正在记录课堂':recordState==='paused'?'录音已暂停':'准备好记录了吗？'}</h3><div class="time" id="record-time">${formatTime(recordSeconds)}</div><div class="wave ${recordState==='recording'?'running':''}">${'<i></i>'.repeat(25)}</div><p class="muted">${recordMode==='hardware'?'模拟录音卡实体按键，小程序同步显示状态':'演示录音计时，不实际调用麦克风'}</p></div>${recordState==='idle'?`<button class="primary" onclick="recordState='recording';render()">${recordMode==='hardware'?'模拟按下录音卡按键':'开始录音'}</button>`:`<div class="bottom-action">${recordMode==='phone'?`<button class="secondary" onclick="recordState=recordState==='paused'?'recording':'paused';render()">${recordState==='paused'?'继续录音':'暂停'}</button>`:''}<button class="primary" onclick="finishRecording()">${recordMode==='hardware'?'模拟按键结束':'结束并保存'}</button></div>`}`,
 transfer:()=>`<span class="pill">录音卡 → 小程序</span><h2 style="margin-top:17px">把课堂带回来</h2><p class="sub">回传后，即可生成转写与课堂笔记</p><div class="device-illustration"><span>●</span><small>YUNI RECORDER</small></div><div class="panel"><h3>课堂录音 · ${formatTime(recordSeconds||2700)}</h3><p class="muted">归属：${esc(course().name)}</p><div class="row"><span class="muted" id="transfer-label">${transferProgress===100?'回传完成':transferProgress?'正在回传，请保持设备连接':'等待回传'}</span><strong id="transfer-percent">${transferProgress}%</strong></div><div class="progress-track"><i id="transfer-bar" style="width:${transferProgress}%"></i></div></div><button class="primary" id="transfer-start" onclick="startTransfer()">${transferProgress===100?'保存课时并生成笔记':transferProgress?'传输进行中':'开始模拟回传'}</button>${transferProgress>0&&transferProgress<100?'<button class="text-btn" onclick="cancelTransfer()">取消回传</button>':''}<div class="banner">传输协议及连接距离由硬件规格确定；此处只演示传输状态。</div>`,
 processing:()=>`<div class="processing center"><div class="record-orb recording">${icon('spark')}</div><h2 id="processing-title">${processingStep===3?'课堂笔记准备好了':'正在整理这堂课'}</h2><p class="sub">${esc(currentName())}</p></div><div class="panel">${['语音转写','生成概要与知识要点','关联原文与音频位置'].map((t,i)=>`<div class="checkline">${t}<span id="process-${i}">${i<processingStep?'✓ 已完成':i===processingStep?'处理中…':'等待'}</span></div>`).join('')}</div><div class="banner">演示依次完成各阶段；真实课堂口音、术语、噪声与远距离收音的转写质量需单独验证。</div><button class="primary" id="process-open" ${processingStep<3?'disabled':''} onclick="go('notes')">打开课堂笔记</button><button class="text-btn" style="display:block;margin:17px auto" onclick="go('home')">返回首页</button>`,
 notes:()=>`<div class="greeting">${esc(course().name)} <span>AI NOTES</span></div><h2 style="font-size:22px">${esc(currentName())}</h2><div class="row note-meta"><span>由课堂录音整理 · 可编辑校正</span><button class="text-btn" onclick="go('edit')">${icon('edit')} 编辑</button></div><div class="segmented">${['概要','知识要点','思维导图'].map((t,i)=>`<button class="${noteTab===i?'on':''}" onclick="noteTab=${i};render()">${t}</button>`).join('')}</div>${noteTab===2?`<div class="panel"><div class="pill">本节课程知识结构</div><div class="map-tree">${['核心概念','知识之间的关系','课堂应用与例子'].map(t=>`<div class="map-node" onclick="noteTab=1;render()">${t}<div class="map-tree"><div class="map-node">相关知识点 · 点击查看</div></div></div>`).join('')}</div></div>`:`<div class="note-block ${study().marked?'marked':''}" id="main-note" oncontextmenu="event.preventDefault();noteMenu()" onpointerdown="holdNote(event)" onpointerup="cancelHold()" onpointerleave="cancelHold()"><div class="row"><h3>${noteTab===0?'课程概要':'01 · 核心知识点'}</h3><span class="pill">${study().marked?'★ 已标重点':'AI 整理'}</span></div><p>${esc(study().note)}</p>${study().remark?`<div class="source-box">我的备注：${esc(study().remark)}</div>`:''}<div class="note-tools"><button onclick="go('edit')">编辑校正</button><button onclick="study().marked=!study().marked;save();render()">${study().marked?'取消重点':'标记重点'}</button><button onclick="openSource(0)">原文 02:18 ↗</button><button aria-label="更多笔记操作" onclick="noteMenu()">•••</button></div></div>${noteTab===1?'<div class="note-block"><h3>02 · 知识之间的联系</h3><p>将本节课的概念与上节课的基础知识串联，并通过课堂例子理解应用条件。</p><div class="note-tools"><button onclick="openSource(1)">原文 08:42 ↗</button></div></div>':'<div class="note-block"><h3>这堂课的学习线索</h3><p>概念理解 → 关系梳理 → 例子应用 → 练习巩固</p></div>'}`}<div class="banner">长按笔记可编辑、标记重点或跳转原文。右下方“•••”也可打开相同操作。</div><div class="bottom-action"><button class="secondary" onclick="go('transcript')">录音与转写</button><button class="primary" onclick="go('review')">考点与复习 →</button></div>`,
 edit:()=>`<div class="greeting">笔记校正 <span>对照原文，更有依据</span></div><label class="label" for="note-edit">笔记内容</label><textarea id="note-edit" class="field edit-area">${esc(study().note)}</textarea><label class="check"><input id="note-mark" type="checkbox" ${study().marked?'checked':''}>标记为复习重点</label><label class="label" for="note-remark">补充我的备注</label><textarea id="note-remark" class="field" rows="2" placeholder="记录自己的理解或疑问">${esc(study().remark||'')}</textarea><div class="row section-title"><strong style="font-size:12px">原始转写对照</strong><button class="text-btn" onclick="editSource=!editSource;$('#edit-source').hidden=!editSource">展开 / 收起</button></div><div class="source-box" id="edit-source" ${editSource?'':'hidden'}><span class="pill">02:18 · 课堂录音</span><p>我们这节课先介绍核心概念，然后看看几个知识点之间是什么关系。大家复习的时候，可以结合刚才讲的例子，再做一下练习。</p><span class="muted">对应笔记来源段落 · 示例转写内容</span></div><div class="bottom-action"><button class="secondary" onclick="go('notes')">取消</button><button class="primary" onclick="saveNote()">保存修改</button></div>`,
 transcript:()=>`<h2 style="font-size:21px">录音与原始转写</h2><p class="sub">${esc(currentName())}</p><div class="player"><button class="play" onclick="playerOn=!playerOn;render()" aria-label="播放或暂停模拟音频">${playerOn?'Ⅱ':'▶'}</button><div><div class="row"><span id="play-time">${formatTime(playerSeconds)}</span><span>45:00 · 模拟回听</span></div><input type="range" min="0" max="2700" value="${playerSeconds}" oninput="playerSeconds=Number(this.value);$('#play-time').textContent=formatTime(playerSeconds)" aria-label="音频进度"></div></div><div class="banner">${transcriptIndex===0?'已定位到笔记引用的 02:18 段落':'点击段落，将模拟播放器定位到对应时间'}。实际音频未嵌入原型。</div>${transcriptData.map(([time,text],i)=>`<div class="transcript ${i===transcriptIndex?'active':''}" onclick="selectTranscript(${i})"><small>${time} &nbsp; 教师</small><p>${text}</p></div>`).join('')}<button class="secondary" onclick="go('notes')">返回笔记</button>`,
 review:()=>`<div class="greeting">${esc(course().name)} <span>REVIEW PLAN</span></div><h2>把重点，再过一遍。</h2><p class="sub">基于本课笔记整理 · 内容为结构示例</p>${[['01','理解核心概念','说出定义、适用条件，并举出一个课堂例子。'],['02','梳理知识联系','区分相近概念，建立概念之间的关系。'],['03','检验应用能力','通过练习检查掌握情况，回到原文校正理解。']].map(([n,t,d])=>`<div class="review-item"><b>${n}</b><div><h3>${t}</h3><p>${d}</p><button class="text-btn" onclick="noteTab=1;go('notes')">回看对应笔记 ↗</button></div></div>`).join('')}<div class="section-title"><strong>建议这样复习</strong></div><div class="panel"><div class="checkline">课后 · 快速回顾<span>读概要与要点</span></div><div class="checkline">次日 · 自测巩固<span>完成一组练习</span></div><div class="checkline">考前 · 查漏补缺<span>回看错题与原文</span></div></div><button class="primary" onclick="go('exam')">开始押题练习 · 3 题</button>`,
 exam:()=>examView(),results:()=>resultsView(),
 ai:()=>`<div class="row"><h2 style="font-size:23px">一起把知识学懂</h2>${icon('spark')}</div><p class="sub">围绕你的笔记回答，每个答案都可追溯</p>${courseSelect('ai-course')}<div class="segmented"><button class="${aiScope==='lesson'?'on':''}" onclick="aiScope='lesson';render()">当前课时</button><button class="${aiScope==='course'?'on':''}" onclick="aiScope='course';render()">整门课程</button></div>${aiScope==='lesson'&&course().lessons.length?`<select class="field" aria-label="选择问答课时" onchange="state.lesson=Number(this.value);save();chats=[];render()">${course().lessons.map((l,i)=>`<option value="${i}" ${i===state.lesson?'selected':''}>${esc(l.name)}</option>`).join('')}</select>`:''}${!chats.length?`<div class="ai-logo">✧</div><h3 class="center">这堂课，哪里还没弄懂？</h3><p class="sub center">从课程重点、概念关系或复习建议开始</p>${['帮我总结这堂课的三个重点','这个知识点该怎么理解？','为我安排一个复习顺序'].map((s,i)=>`<button class="suggestion" onclick="askAI(${i})">${s} <span style="float:right">↗</span></button>`).join('')}`:chats.map(c=>`<div class="bubble ${c.role==='user'?'user':''}">${esc(c.text)}${c.role==='assistant'&&c.source?'<br><button class="text-btn" onclick="go(\'notes\')">来源：课程笔记 · 课程概要 ↗</button>':''}</div>`).join('')}<div class="chat-input"><input class="field" id="chat-input" placeholder="问问这门课的内容…" onkeydown="if(event.key==='Enter')askAI()"><button class="primary" onclick="askAI()" aria-label="发送问题">↑</button></div><p class="fine center">演示问答，仅用于体验引用与跳转；未接入 AI。</p>`,
 mine:()=>`<div class="course-heading"><div class="avatar">芋</div><div><h2 style="font-size:22px">${state.logged?'微信体验用户':'欢迎来到芋泥'}</h2><p class="sub">${state.logged?'把学到的，变成自己的。':'登录后关联课程与录音设备'}</p></div></div>${!state.logged?'<button class="primary" onclick="go(\'login\')">微信登录</button>':''}<div class="stat-row"><div><b>${state.courses.length}</b><span>我的课程</span></div><div><b>${state.courses.reduce((n,c)=>n+c.lessons.length,0)}</b><span>课时记录</span></div><div><b>${state.courses.reduce((n,c)=>n+c.lessons.filter(l=>l.study?.marked).length,0)}</b><span>标记重点</span></div></div><div class="panel"><div class="row"><h3>课堂笔记权益</h3><span class="pill">演示额度</span></div><p class="muted">剩余 <b style="color:var(--green);font-size:23px">29</b> 次 AI 课堂笔记</p><button class="text-btn" onclick="quotaInfo()">查看额度说明 ↗</button></div><div class="menu-row" onclick="go('device')">${icon('device')}我的录音卡<small>${state.bound?'已绑定 · 86%':'未绑定'}</small><span>›</span></div><div class="menu-row" onclick="go('home')">${icon('book')}我的课程<span class="chevron">›</span></div><div class="menu-row" onclick="go('notes')">${icon('heart')}回顾笔记重点<span class="chevron">›</span></div><div class="menu-row" onclick="sheet('关于芋泥','<p>课堂录音 → AI 笔记 → 考点复习 → 试卷批阅。</p><p>小程序交互原型 v0.1。数据仅保存在当前浏览器。</p>')">${icon('spark')}关于芋泥<span class="chevron">›</span></div>${state.logged?'<button class="text-btn" style="margin-top:24px" onclick="state.logged=false;save();render();toast(\'已退出演示账户\')">退出登录</button>':''}`,
 device:()=>`<div class="row"><h2 style="font-size:23px">你的随身课堂记录员</h2></div><p class="sub">${state.bound?'芋泥录音卡 · 设备 YN-001（演示）':'首次使用，请绑定你的录音卡'}</p><div class="device-illustration"><span>●</span><small>YUNI RECORDER</small></div>${state.bound?`<div class="stat-row"><div><b>86<small>%</small></b><span>设备电量</span></div><div><b>12.8<small>G</small></b><span>可用 / 16G</span></div><div><b style="font-size:16px;padding:4px">已连接</b><span>连接状态（模拟）</span></div></div><button class="primary" onclick="startMode('hardware')">${icon('mic')} 查看录音状态</button><div class="panel"><div class="row"><h3>待回传录音</h3><span class="pill">1 个文件</span></div><p class="muted">课堂录音 · 45:00 · 录音卡本地文件</p><label class="label">保存到课程</label>${courseSelect('device-course')}<button class="secondary" style="margin-top:12px" onclick="transferProgress=0;go('transfer')">回传并整理</button></div><button class="text-btn" onclick="sheet('解除设备绑定','<p>仅解除原型中的设备关联；已归档笔记保留。</p><button class=\"primary\" onclick=\"state.bound=false;save();render()\">确认解除绑定</button>')">解除绑定</button>`:`<div class="banner">打开录音卡并置于附近。正式连接方式与权限以硬件方案为准。</div><button class="primary" onclick="bindDevice()">查找并绑定设备</button><p class="fine center">演示发现与绑定状态，不调用真实连接权限。</p>`}`
};
const transcriptData=[['02:18','我们这节课先介绍核心概念，然后看看几个知识点之间是什么关系。大家复习的时候，可以结合刚才讲的例子，再做一下练习。'],['08:42','这里要注意两个概念的区别，不能只记定义，还要理解它们各自的适用条件。'],['16:05','接下来用一个课堂例子来说明。请先想一想应当选择什么方法，再检查推理过程。'],['32:10','课后可以回顾今天的知识点，完成练习，把不确定的地方标记下来。']];
function login(){if(!$('#agreement').checked)return toast('请先阅读并勾选协议说明');sheet('微信授权 · 模拟',`<p>芋泥申请使用你的微信账户身份建立关联。</p><button class="primary" onclick="completeLogin()">同意并继续</button><button class="secondary" style="margin-top:10px" onclick="closeSheet();toast('已取消授权，可重新登录')">取消授权</button>`)}
function completeLogin(){state.logged=true;save();const next=pendingLoginAction;pendingLoginAction=null;go('home');if(next)next();toast('模拟登录成功')}
function bindDevice(){if(!state.logged){pendingLoginAction=()=>go('device');sheet('先登录，关联你的录音卡','<p>设备将绑定到微信账户，便于管理课堂录音与笔记。</p><button class="primary" onclick="go(\'login\')">前往微信登录</button>');return}sheet('发现附近设备','<div class="device-strip">'+icon('device')+'<div><strong>芋泥录音卡 YN-001</strong><small>可绑定 · 演示设备</small></div></div><button class="primary" onclick="state.bound=true;save();render();toast(\'设备绑定成功（模拟）\')">确认绑定</button>')}
function startMode(mode){if(!state.logged){pendingLoginAction=()=>startMode(mode);go('login');toast('登录后开始记录课堂');return}if(mode==='hardware'&&!state.bound){go('device');toast('请先绑定录音卡');return}recordMode=mode;recordState='idle';recordSeconds=0;go('record')}
function formatTime(n){return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
function startRecordTimer(){timer=setInterval(()=>{recordSeconds++;if($('#record-time'))$('#record-time').textContent=formatTime(recordSeconds)},1000)}
function finishRecording(){recordState='paused';clearInterval(timer);sheet('结束这次课堂录音？',`<p>录音时长 ${formatTime(recordSeconds)}，保存到「${esc(course().name)}」。</p><button class="primary" onclick="recordState='idle';${recordMode==='hardware'?"transferProgress=0;go('transfer')":"saveRecordingDialog()"}">结束并${recordMode==='hardware'?'回传':'归档'}</button><button class="secondary" style="margin-top:10px" onclick="recordState='recording';render()">继续录音</button>`)}
function saveRecordingDialog(){sheet('保存这堂课',`<label class="label">课时名称</label><input id="lesson-name" class="field" maxlength="40" value="第 ${course().lessons.length+1} 课 · 新课堂记录"><p class="muted">录音将归档到 ${esc(course().name)}</p><button class="primary" onclick="addLesson()">保存并生成笔记</button>`)}
function addLesson(){const name=$('#lesson-name').value.trim();if(!name)return toast('请填写课时名称');course().lessons.unshift({name,ready:false,duration:formatTime(recordSeconds||2700)});state.lesson=0;save();beginProcessing()}
function beginProcessing(){if(!lesson()){saveRecordingDialog();return}processingStep=0;go('processing')}
function startProcessingTimer(){timer=setInterval(()=>{processingStep++;if(processingStep>=3){clearInterval(timer);if(lesson())lesson().ready=true;save();$('#processing-title').textContent='课堂笔记准备好了';$('#process-open').disabled=false}for(let i=0;i<3;i++)$('#process-'+i).textContent=i<processingStep?'✓ 已完成':i===processingStep?'处理中…':'等待'},1200)}
function startTransfer(){if(transferProgress===100){saveRecordingDialog();return}if(transferProgress>0)return;transferProgress=5;render()}
function startTransferTimer(){timer=setInterval(()=>{transferProgress=Math.min(100,transferProgress+19);$('#transfer-percent').textContent=transferProgress+'%';$('#transfer-bar').style.width=transferProgress+'%';if(transferProgress===100){clearInterval(timer);render()}},550)}
function cancelTransfer(){clearInterval(timer);transferProgress=0;render();toast('回传已取消，录音仍保留在设备，可重试')}
function importAudio(){if(!state.logged){pendingLoginAction=importAudio;go('login');toast('登录后导入自己的课堂录音');return}sheet('导入课堂录音',`<p>可选择本地音频展示文件名，或用示例体验。文件不会上传，也不会被实际转写。</p><input class="field" id="audio-file" type="file" accept=".m4a,.mp3,.wav,.aac" onchange="checkAudio(this)"><p id="audio-choice" class="muted">支持 M4A / MP3 / WAV / AAC</p><button class="primary" onclick="recordSeconds=2700;saveRecordingDialog()">使用示例录音体验</button><button class="secondary" id="import-selected" style="margin-top:10px" disabled onclick="recordSeconds=2700;saveRecordingDialog()">使用所选文件演示</button>`)}
function checkAudio(input){const f=input.files[0];const ok=f&&/\.(m4a|mp3|wav|aac)$/i.test(f.name);$('#audio-choice').textContent=ok?`${f.name} · 仅演示，时长使用占位值`: '请选择支持的音频格式';$('#import-selected').disabled=!ok}
function enterStage(r,i){if(!lesson()?.ready){if(i===0)toast('录音已保存，生成后可查看转写');else toast('请先完成转写与笔记生成');return}go(r)}
function saveNote(){study().note=$('#note-edit').value;study().marked=$('#note-mark').checked;study().remark=$('#note-remark').value;save();go('notes');toast('笔记已保存')}
let holdTimer;
function holdNote(e){if(e.target.closest('button'))return;holdTimer=setTimeout(noteMenu,650)}
function cancelHold(){clearTimeout(holdTimer)}
function noteMenu(){sheet('这段笔记',`<button class="secondary" onclick="go('edit')">编辑与补充备注</button><button class="secondary" style="margin-top:10px" onclick="study().marked=!study().marked;save();render()">${study().marked?'取消重点标记':'标记为复习重点'}</button><button class="primary" onclick="openSource(0)">跳转原文 · 02:18</button>`)}
function openSource(i){transcriptIndex=i;playerSeconds=[138,522,965,1930][i];go('transcript')}
function selectTranscript(i){transcriptIndex=i;playerSeconds=[138,522,965,1930][i];render()}
function startPlayerTimer(){timer=setInterval(()=>{playerSeconds=Math.min(2700,playerSeconds+1);$('#play-time').textContent=formatTime(playerSeconds);$('#screen input[type=range]').value=playerSeconds;if(playerSeconds===2700){playerOn=false;clearInterval(timer)}},1000)}
const questions=[{type:'单选题',title:'复习本节课时，哪一种方式更有助于理解知识？',options:['只记忆术语名称','结合定义、适用条件与课堂例子','跳过概念直接猜题','仅阅读试卷答案'],answer:1,explain:'结合定义、适用条件和例子，才能检查对知识的理解。'}, {type:'多选题',title:'哪些材料可以作为校正 AI 笔记的依据？',options:['对应的课堂录音','原始转写与上下文','未经核对的猜测'],answer:[0,1],explain:'应回溯课堂录音和原始转写，并结合上下文校正，不应依靠猜测。'}, {type:'简答题',title:'请简要描述你的课后复习顺序。',answer:'先回顾概要与知识要点，再完成练习，最后结合错题回看原文。',explain:'参考顺序：回顾知识 → 自测 → 定位薄弱点 → 回溯原文。本原型不对主观题执行真实 AI 评分。'}];
function examView(){const q=questions[question];return `<div class="row"><span class="pill">${q.type}</span><small class="muted">${question+1} / 3</small></div><div class="question-nav">${questions.map((_,i)=>`<button class="${study().answers[i]!==null?'done':''} ${question===i?'on':''}" onclick="question=${i};render()">${i+1}</button>`).join('')}</div><div class="question-title">${q.title}</div>${q.options?q.options.map((t,i)=>`<button class="exam-option ${(question===1?(study().answers[1]||[]).includes(i):study().answers[question]===i)?'selected':''}" onclick="chooseAnswer(${i})"><b>${String.fromCharCode(65+i)}</b>${t}</button>`).join(''):`<textarea class="field edit-area" placeholder="输入你的复习思路…" oninput="study().answers[2]=this.value.trim()?this.value:null;save()">${esc(study().answers[2]||'')}</textarea>`}<p class="muted">${question===1?'本题可选择多个答案。':'答案会在切换题目时保留。'}</p><div class="bottom-action"><button class="secondary" ${question===0?'disabled':''} onclick="question--;render()">上一题</button><button class="primary" onclick="${question===2?'confirmSubmit()':'question++;render()'}">${question===2?'提交试卷':'下一题'}</button></div><button class="text-btn" style="display:block;margin:20px auto" onclick="confirmSubmit()">提前提交</button>`}
function chooseAnswer(i){if(question===1){let a=study().answers[1]||[];a=a.includes(i)?a.filter(x=>x!==i):[...a,i];study().answers[1]=a.length?a:null}else study().answers[question]=i;save();render()}
function confirmSubmit(){const missing=study().answers.filter(a=>a===null).length;sheet('提交这次练习？',`<p>${missing?`还有 ${missing} 道题未作答，提交后会标记为未答。`:'已完成全部题目，可以查看批阅结果。'}</p><button class="primary" onclick="study().submitted=true;save();go('results')">确认提交</button><button class="secondary" style="margin-top:10px" onclick="closeSheet()">继续检查</button>`)}
function resultsView(){if(!study().submitted)return `<div class="empty">完成一组练习后，查看逐题批阅与复习建议。</div><button class="primary" onclick="go('exam')">开始练习</button>`;const correct=[study().answers[0]===1,JSON.stringify([...(study().answers[1]||[])].sort())==='[0,1]'];return `<div class="greeting">练习反馈 <span>REVIEW & REFLECT</span></div><div class="center panel"><div class="score">${correct.filter(Boolean).length}<small> / 2</small></div><h3>客观题答对数量</h3><p class="muted">简答题提供参考答案 · 原型未执行 AI 评分</p></div><div class="banner">${correct.every(Boolean)?'客观题全部答对，结合简答参考答案再梳理复习思路。':'建议回看概念理解与原文核对方法，再做一次练习。'} <button class="text-btn" onclick="go('review')">去复习 ↗</button></div>${questions.map((q,i)=>`<div class="note-block"><div class="row"><h3>第 ${i+1} 题 · ${q.type}</h3><span class="pill ${i<2&&!correct[i]?'orange':''}">${i===2?'参考解析':correct[i]?'正确':'待巩固'}</span></div><p>${q.title}</p><div class="answer-box"><div class="${i<2&&!correct[i]?'wrong':''}">你的答案<br>${esc(study().answers[i]===null?'未作答':i===2?study().answers[i]:i===1?study().answers[i].map(n=>String.fromCharCode(65+n)).join('、'):String.fromCharCode(65+study().answers[i]))}</div><div>参考答案<br>${i===0?'B':i===1?'A、B':q.answer}</div></div><p>${q.explain}</p></div>`).join('')}<div class="bottom-action"><button class="secondary" onclick="window.print()">打印 / 存为 PDF</button><button class="primary" onclick="study().answers=[null,null,null];study().submitted=false;question=0;save();go('exam')">再练一次</button></div>`}
function askAI(index){const suggestions=['帮我总结这堂课的三个重点','这个知识点该怎么理解？','为我安排一个复习顺序'];const text=index===undefined?$('#chat-input').value.trim():suggestions[index];if(!text)return;if(aiScope==='course'&&!lesson()?.ready){const sourceIndex=course().lessons.findIndex(l=>l.ready);if(sourceIndex>=0)state.lesson=sourceIndex}chats.push({role:'user',text});const available=aiScope==='lesson'?Boolean(lesson()?.ready):course().lessons.some(l=>l.ready);chats.push({role:'assistant',source:available,text:available?'这是基于笔记的演示回答：\n\n1. 先理解本课的核心概念与适用条件。\n2. 结合课堂例子，梳理知识之间的联系。\n3. 完成练习，再回溯不确定的原文段落。\n\n正式版本将依据你选定的课程内容作答；本原型不生成真实答案。':'这门课程还没有可用笔记。请先录制一个课时并完成整理，再基于笔记提问。'});render();$('#screen').scrollTop=$('#screen').scrollHeight}
function quotaInfo(){sheet('课堂笔记额度',`<p>视频中的开启确认显示「剩余 29 次，消耗 1 次」。此原型保留次数展示，演示过程中不扣减。</p><p>新增清单的免费额度与后续付费能力待验证，暂未设置价格、套餐或购买流程。</p><button class="primary" onclick="closeSheet()">知道了</button>`)}
goWithoutHistory(pages[location.hash.slice(1)]?location.hash.slice(1):'home');
